### ISSUE TITLE
"Call object has no attribute value" error during instrumentation for TraceAll Analysis

### ISSUE THREAD

**Issue by piyush-bajaj** [sola-st/DynaPyt#16]
While trying to run the instrumentation for the project **https://github.com/pallets/click.git** , **src** folder getting the error as **AttributeError: 'Call' object has no attribute 'value'** for one of the files named **core.py**

**Environment details:**
Docker container with ubuntu:latest as base image

Steps to reproduce:
```
git clone https://github.com/pallets/click.git click
cd click
virtualenv vm
source vm/bin/activate
pip install .
pip install requirements/tests.txt
pip install dynapyt libcst pytest pytest-xdist
python -m dynapyt.run_instrumentation --directory ./src --analysis TraceAll

```

**Detailed output:**
```
Done with ./src/click/globals.py
Done with ./src/click/__init__.py
Done with ./src/click/_textwrap.py
Done with ./src/click/exceptions.py
Done with ./src/click/formatting.py
Done with ./src/click/_winconsole.py
Done with ./src/click/shell_completion.py
Done with ./src/click/decorators.py
Done with ./src/click/testing.py
Done with ./src/click/utils.py
Done with ./src/click/termui.py
Done with ./src/click/parser.py
Done with ./src/click/_compat.py
Done with ./src/click/_termui_impl.py
Done with ./src/click/types.py
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/dynapyt/instrument/instrument.py", line 78, in <module>
    instrument_file(file_path, selected_hooks)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/dynapyt/instrument/instrument.py", line 54, in instrument_file
    instrumented_code = instrument_code(src, file_path, iids, selected_hooks)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/dynapyt/instrument/instrument.py", line 42, in instrument_code
    instrumented_ast = ast_wrapper.visit(instrumented_code)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/metadata/wrapper.py", line 204, in visit
    return self.module.visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/module.py", line 90, in visit
    result = super(Module, self).visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/module.py", line 74, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/statement.py", line 1940, in _visit_and_replace_children
    body=visit_required(self, "body", self.body, visitor),
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/statement.py", line 698, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/statement.py", line 1797, in _visit_and_replace_children
    body=visit_required(self, "body", self.body, visitor),
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/statement.py", line 698, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 227, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 193, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/statement.py", line 443, in _visit_and_replace_children
    body=visit_sequence(self, "body", self.body, visitor),
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 177, in visit_sequence
    return tuple(visit_iterable(parent, fieldname, children, visitor))
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 159, in visit_iterable
    new_child = child.visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/base.py", line 228, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/statement.py", line 302, in _visit_and_replace_children
    value=visit_optional(self, "value", self.value, visitor),
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/internal.py", line 110, in visit_optional
    result = node.visit(visitor)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_nodes/base.py", line 237, in visit
    leave_result = visitor.on_leave(self, with_updated_children)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/matchers/_visitors.py", line 522, in on_leave
    retval = CSTTransformer.on_leave(self, original_node, updated_node)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/libcst/_visitors.py", line 71, in on_leave
    updated_node = leave_func(original_node, updated_node)
  File "/DyPyBench/Project/project10/vm/lib/python3.10/site-packages/dynapyt/instrument/CodeInstrumenter.py", line 644, in leave_Call
    if (((len(list(name_source)) > 0) and (list(name_source)[0].source == QualifiedNameSource.BUILTIN) and (original_node.func.value in site_sensitive_functions)) or 
AttributeError: 'Call' object has no attribute 'value'
Error at ./src/click/core.py
#################### Instrumentation took 5.104191541671753
```

**Comment by AryazE** [comment]
[Line 652](https://github.com/sola-st/DynaPyt/blob/main/src/dynapyt/instrument/CodeInstrumenter.py#L652) should be modified to something like:
```python
if (((len(list(name_source)) > 0) and (list(name_source)[0].source == QualifiedNameSource.BUILTIN) and (m.matches(original_node.func, m.Name())) and (original_node.func.value in site_sensitive_functions)) or 
```
But this needs testing.
