### ISSUE TITLE
Missing dependency: libcst is not installed when installing dynapyt using pip

### ISSUE THREAD

**Issue by nimamg** [sola-st/DynaPyt#25]
Installing dynapyt using pip does not install libcst

Log from running TraceAll after fresh install:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<project_dir>/venv/lib/python3.11/site-packages/dynapyt/run_analysis.py", line 25, in <module>
    import dynapyt.runtime as rt
  File "<project_dir>/venv/lib/python3.11/site-packages/dynapyt/runtime.py", line 3, in <module>
    import libcst as cst
ModuleNotFoundError: No module named 'libcst'
```

**Comment by AryazE** [comment]
It seems the issue is fixed. Feel free to reopen this issue if it is not.
