### ISSUE TITLE
Command line crash

### ISSUE THREAD

**Issue by khatchad** [sola-st/DynaPyt#41]
```bash
root@123fd1ef05ea:/dynapyt# python -m dynapyt.run_instrumentation
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/dynapyt/run_instrumentation.py", line 74, in <module>
    instrument_dir(start, analysis, use_external_dir)
  File "/usr/local/lib/python3.10/dist-packages/dynapyt/run_instrumentation.py", line 29, in instrument_dir
    for dir_path, dir_names, file_names in walk(start):
  File "/usr/lib/python3.10/os.py", line 343, in walk
    return _walk(fspath(top), topdown, onerror, followlinks)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by AryazE** [comment]
Thanks for raising this issue! Feel free to reopen is it still crashes in some cases.
